POST http://localhost:3003/api/blogs/
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1lbWUiLCJpZCI6IjVkODY3Y2I5YzQ0MTcwMzMwNDAzMThiNCIsImlhdCI6MTU2OTE3MTI4Nn0.Wm4kO0MbhpWtO6Zxl6bwYbW0_f_szOpKhebRCO9z_bE
Content-Type: application/json

{
    "title": "Otsikko9",
    "author": "Kirjailija9",
    "url": "http://inter.net/kirja?id=9",
    "likes": 9
}