DELETE http://localhost:3003/api/blogs/5e121b8e1e532739f8406cac
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InR1IiwiaWQiOiI1ZTEyMWIzNzFlNTMyNzM5Zjg0MDZjYWEiLCJpYXQiOjE1NzgyNDUxOTl9.ziZnjxP9ZKNyzuKVsuksf8M8nwv45z14dU6_X72XurU

{}