POST http://localhost:3003/api/blogs/
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Iml0ZSIsImlkIjoiNWQ4N2I4NDY4YWIyNzYyMTA4Y2E1ODBlIiwiaWF0IjoxNTY5MTc1NjgzfQ.IbyoZ7Yyq2Z6NZQUtQfICAqQQdbdyzjCVaWo6bHthN0
Content-Type: application/json

{
    "title": "S-mies",
    "author": "Taiteilija",
    "url": "http://inter.net/teos?id=123",
    "likes": 987
}